// <auto-generated />
using System;
using KeySkills.Core.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KeySkills.Core.Data.Sqlite.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("KeySkills.Core.Models.Keyword", b =>
                {
                    b.Property<int>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KeywordId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Keywords");

                    b.HasData(
                        new
                        {
                            KeywordId = 1,
                            Name = ".NET",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(\\.net|dot\\p{Z}*net)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 2,
                            Name = "ASP.NET",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(asp\\p{Z}*\\.\\p{Z}*net)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 3,
                            Name = "C#",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(c#|c\\p{Z}*sharp)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 4,
                            Name = "F#",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(f#|f\\p{Z}*sharp)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 5,
                            Name = "VB.NET",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(vb\\p{Z}*\\.\\p{Z}*net)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 6,
                            Name = "WPF",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(wpf|windows\\p{Z}*presentation\\p{Z}*foundation)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 7,
                            Name = "WinForms",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(winforms|windows\\p{Z}*forms)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 8,
                            Name = "WCF",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(wcf|windows\\p{Z}*communication\\p{Z}*foundation)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 9,
                            Name = "ADO.NET",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(ado\\p{Z}*\\.\\p{Z}*net)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 10,
                            Name = "Entity Framework",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(ef|entity\\p{Z}*framework)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 11,
                            Name = "Dapper",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(dapper)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 12,
                            Name = "NHibernate",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(nhibernate)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 13,
                            Name = "Xamarin",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(xamarin)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 14,
                            Name = "JavaScript",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(js|javascript)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 15,
                            Name = "TypeScript",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(typescript)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 16,
                            Name = "ReactJS",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(react|react\\p{P}*\\p{Z}*js)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 17,
                            Name = "Angular",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(angular)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 18,
                            Name = "AngularJS",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(angular\\p{P}*\\p{Z}*js)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 19,
                            Name = "Vue.js",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(vue|vue\\p{P}*\\p{Z}*js)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 20,
                            Name = "Node.js",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(node\\p{P}*\\p{Z}*js)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 21,
                            Name = "JQuery",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(jquery)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 22,
                            Name = "Redux",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(redux)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 23,
                            Name = "Svelte",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(svelte)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 24,
                            Name = "Express",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(express)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 25,
                            Name = "Nuxt",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(nuxt)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 26,
                            Name = "Gulp",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(gulp)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 27,
                            Name = "Grunt",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(grunt)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 28,
                            Name = "Webpack",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(webpack)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 29,
                            Name = "Apollo",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(apollo)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 30,
                            Name = "Ionic",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(ionic)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 31,
                            Name = "Electron",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(electron)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 32,
                            Name = "Java",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(java)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 33,
                            Name = "Spring",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(spring)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 34,
                            Name = "Maven",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(maven)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 35,
                            Name = "Gradle",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(gradle)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 36,
                            Name = "Python",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(python)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 37,
                            Name = "Django",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(django)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 38,
                            Name = "Flask",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(flask)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 39,
                            Name = "SQL",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(sql|pgsql)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 40,
                            Name = "PostgreSQL",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(postgresql|postgres)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 41,
                            Name = "MySQL",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(mysql)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 42,
                            Name = "Oracle",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(oracle)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 43,
                            Name = "SQL Server",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(sql\\p{P}*\\p{Z}*server)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 44,
                            Name = "MariaDB",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(mariadb)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 45,
                            Name = "SQLite",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(sqlite)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 46,
                            Name = "Db2",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(db2)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 47,
                            Name = "MongoDB",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(mongodb)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 48,
                            Name = "Redis",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(redis)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 49,
                            Name = "NoSQL",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(nosql)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 50,
                            Name = "Prometheus",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(prometheus)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 51,
                            Name = "InfluxDB",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(influxdb)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 52,
                            Name = "HTML",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(html\\d?|xhtml)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 53,
                            Name = "JSON",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(json)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 54,
                            Name = "XML",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(xml)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 55,
                            Name = "CSS",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(css)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 56,
                            Name = "Less",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(less)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 57,
                            Name = "Sass",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(sass)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 58,
                            Name = "Bootstrap",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(bootstrap)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 59,
                            Name = "Ruby",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(ruby)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 60,
                            Name = "Ruby On Rails",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(rails|ror|ruby\\p{P}*\\p{Z}*on\\p{P}*\\p{Z}*rails)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 61,
                            Name = "Sinatra",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(sinatra)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 62,
                            Name = "C++",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(c\\+\\+|cpp|c\\p{P}*\\p{Z}*plus\\p{P}*\\p{Z}*plus)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 63,
                            Name = "PHP",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(php)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 64,
                            Name = "Laravel",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(laravel)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 65,
                            Name = "Symfony",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(symfony)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 66,
                            Name = "CakePHP",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(cakephp)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 67,
                            Name = "Yii",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(yii)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 68,
                            Name = "Zend",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(zend)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 69,
                            Name = "Drupal",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(drupal)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 70,
                            Name = "Scala",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(scala)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 71,
                            Name = "Sbt",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(sbt)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 72,
                            Name = "Akka",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(akka)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 73,
                            Name = "Spark",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(spark)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 74,
                            Name = "Kafka",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(kafka)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 75,
                            Name = "Flink",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(flink)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 76,
                            Name = "Hadoop",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(hadoop)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 77,
                            Name = "Kotlin",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(kotlin)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 78,
                            Name = "Golang",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(go|golang)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 79,
                            Name = "ECMAScript",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(ecma\\p{P}*\\p{Z}*script|es\\d?)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 80,
                            Name = "Clojure",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(clojure)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 81,
                            Name = "ClojureScript",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(clojurescript)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 82,
                            Name = "Lisp",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(lisp)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 83,
                            Name = "Rust",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(rust)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 84,
                            Name = "Elm",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(elm)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 85,
                            Name = "Haskell",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(haskell)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 86,
                            Name = "RabbitMQ",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(rabbitmq)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 87,
                            Name = "Elasticsearch",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(elasticsearch)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 88,
                            Name = "Lucene",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(lucene)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 89,
                            Name = "Docker",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(docker)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 90,
                            Name = "Kubernetes",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(kubernetes)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 91,
                            Name = "Mesos",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(mesos)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 92,
                            Name = "AWS",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(aws|amazon\\p{P}*\\p{Z}*web\\p{P}*\\p{Z}*services)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 93,
                            Name = "Azure",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(azure)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 94,
                            Name = "GCP",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(gcp|google\\p{P}*\\p{Z}*cloud\\p{P}*\\p{Z}*platform)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 95,
                            Name = "Heroku",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(heroku)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 96,
                            Name = "OpenShift",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(openshift)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 97,
                            Name = "Cloud Foundry",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(cloud\\p{P}*\\p{Z}*foundry)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 98,
                            Name = "Jenkins",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(jenkins)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 99,
                            Name = "JIRA",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(jira)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 100,
                            Name = "iOS",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(ios)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 101,
                            Name = "macOS",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(macos)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 102,
                            Name = "Swift",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(swift)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 103,
                            Name = "Objective-C",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(objective\\p{P}*\\p{Z}*c)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 104,
                            Name = "Android",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(android)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 105,
                            Name = "Windows",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(windows)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 106,
                            Name = "Linux",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(linux)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 107,
                            Name = "Debian",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(debian)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 108,
                            Name = "Ubuntu",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(ubuntu)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 109,
                            Name = "Fedora",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(fedora)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 110,
                            Name = "CentOS",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(centos)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 111,
                            Name = "RedHat",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(redhat)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 112,
                            Name = "Unix",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(unix)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 113,
                            Name = "SOLID",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(solid)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 114,
                            Name = "Microservices",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(microservices)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 115,
                            Name = "REST",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(rest)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 116,
                            Name = "GraphQL",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(graphql)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        },
                        new
                        {
                            KeywordId = 117,
                            Name = "gRPC",
                            Pattern = "(^|[\\p{C}\\p{P}\\p{S}\\p{Z}]+)(grpc)([\\p{C}\\p{P}\\p{S}\\p{Z}]+|$)"
                        });
                });

            modelBuilder.Entity("KeySkills.Core.Models.Vacancy", b =>
                {
                    b.Property<int>("VacancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VacancyId");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("KeySkills.Core.Models.VacancyKeyword", b =>
                {
                    b.Property<int>("VacancyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeywordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VacancyId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("VacancyKeywords");
                });

            modelBuilder.Entity("KeySkills.Core.Models.VacancyKeyword", b =>
                {
                    b.HasOne("KeySkills.Core.Models.Keyword", "Keyword")
                        .WithMany("Vacancies")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeySkills.Core.Models.Vacancy", "Vacancy")
                        .WithMany("Keywords")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
